---
- hosts: all
  become: true
  tasks:
    - name: install apt-transport-https
      apt:
        name: apt-transport-https
        state: present
        force: yes
        update_cache: yes
    - name: add skype repo key
      apt_key:
        url: https://repo.skype.com/data/SKYPE-GPG-KEY
    - name: add neofetch key
      apt_key:
        url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
    - name: add mopidy key
      apt_key:
        url: https://apt.mopidy.com/mopidy.gpg
    - name: add apt repos
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - deb [arch=amd64] https://repo.skype.com/deb stable main
        - deb http://us.archive.ubuntu.com/ubuntu/ xenial multiverse
        - deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
        - deb http://dl.bintray.com/dawidd6/neofetch jessie main
    - name: add mopidy repo
      shell: sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/jessie.list
    - name: install skype
      apt:
        name: skypeforlinux
    - name: use up to date repo for i3 install
      shell: sudo echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" >> /etc/apt/sources.list.d/sur5r-i3.list
    - name: install packages on Debian/Ubuntu
      apt:
        name: "{{ item }}"
        state: present
        force: yes
        update_cache: yes
      with_items:
        - automake
        - autoconf
        - autotools-dev
        - build-essential
        - cmake
        - clang
        - curl
        - docker.io
        - dunst
        - ffmpeg
        - flashplugin-installer
        - gcc
        - gccgo
        - gcc-multilib
        - gdb
        - gtk-redshift
        # this probably isn't needed, since you need git to
        # clone the repo locally anyways
        - git
        - g++
        - htop
        - i3
        - i3-wm
        - i3lock
        - i3status
        - keychain
        - libasound2-dev
        - libfftw3-dev
        - libmysqlclient-dev
        - libncursesw5-dev
        - libssl-dev
        - libxml2-dev
        - libxslt1-dev
        - mopidy
        - mopidy-spotify
        - mopidy-alsamixer
        - ncmpcpp
        - neofetch
        - openconnect
        - python
        - python-all
        - python-all-dev
        - python-dev
        - python-dev
        - python-pip
        - rxvt-unicode
        - redshift
        - rofi
        - scrot
        - silversearcher-ag
        - ttf-ancient-fonts
        - unzip
        - virtualbox-qt
        - virtualenv
        - virtualenvwrapper
        - vagrant
        - vlc
        - vim
        - zip
        - zsh
        # for keepassx
        - qtbase5-dev
        - libqt5x11extras5-dev
        - qttools5-dev 
        - qttools5-dev-tools
        - libgcrypt20-dev
        - zlib1g-dev
        - libxi-dev
        - libxtst-dev
        - keepassx
        # for obs
        - pkg-config
        - cmake
        - qtbase5-dev
        - checkinstall
        - libx11-dev
        - libgl1-mesa-dev
        - libpulse-dev
        - libxcomposite-dev
        - libxinerama-dev
        - libv4l-dev
        - libudev-dev
        - libfreetype6-dev
        - libfontconfig-dev
        # this is also in keepassx - libqt5x11extras5-dev
        - libx264-dev
        - libxcb-xinerama0-dev
        - libxcb-shm0-dev
        - libjack-jackd2-dev
        - libcurl4-openssl-dev
        - libavcodec-dev
        - libavfilter-dev
        - libavdevice-dev
        - libfdk-aac-dev
