---
- hosts: all
  vars:
    local_scripts_dir: "{{ scripts_dir }}"
  tasks:
    - name: Run the equivalent of "pacman -Syu" as a separate step
      become: true
      pacman:
        update_cache: yes
        upgrade: yes
    - name: install packages
      become: true
      pacman:
        name: "{{ item }}"
      with_items:
        - alacritty
        - alsa-utils
        - ansible
        - base-devel
        - bat
        - blueman
        - bluez
        - bluez-utils
        - breeze
        # because hangouts
        - chromium
        - code
        - discord
        - dunst
        - docker
        - docker-buildx
        - docker-compose
        - element-desktop
        - ffmpeg-compat-57
        - firefox-developer-edition
        # this probably isn't needed, since you need git to
        # clone the repo locally anyways
        - git
        - github-cli
        - gnupg
        - goland
        - goland-jre
        - graphviz
        - gucharmap
        - hugo
        - i3
        - imagemagick
        - jq
        - kakasi
        - kdenlive
        - libinput
        - libreoffice-still
        - mpv
        - msr-tools
        - nautilus
        - neofetch
        - neovim
        - noto-fonts-emoji
        - obs-studio
        - openjpeg
        - openssh
        - otf-ipafont # japanese
        - pacman-contrib
        - pavucontrol
        - poppler
        - pulseaudio
        - pulseaudio-alsa
        - pychess
        - ranger
        - redshift
        - ripgrep
        - rofi
        - rust
        - shellcheck
        - spotifyd
        - spotify
        - telegram-desktop
        - ttf-kanjistrokeorder
        - unzip
        - usbutils
        - vim
        - vlc
        - xdotool
        - xorg
        - yarn # for prometheus
        - zenity
        - zsh
    - name: ensure git directory exists
      file:
        path: /home/callum/git
        state: directory
        owner: callum
        group: callum
        mode: 0755
    - name: install AUR packages
      aur: 
        use: yay
        name: "{{ item }}"
      with_items:
        - anki-git
        - fcitx-qt6
        - fcitx-mozc
        - fcitx-qt5
        - kcm-fcitx
        - fcitx-gtk2
        - fcitx-gtk3
        - jsonnet
        - keepassx2
        - lenovo-throttling-fix-git
        - mecab-ipadic
        - notion-app
        - nvm
        - pulseaudio-ctl
        - s-tui
        - slack-desktop
        - solaar
        - spotify-tui
        - stockfish
        - tanka
        - ttf-kopubworld # korean
        - ttf-symbola
        - ttf-unifont
        - visual-studio-code-bin
    - name: change shell to zsh
      become: true   
      shell: chsh -s /usr/bin/zsh callum
    - name: set timezone
      become: true
      shell: timedatectl set-timezone Canada/Pacific
    - name: enable timezone syncing daemon
      become: true
      shell: systemctl enable systemd-timesyncd
