---
- hosts: all
  vars:
    local_scripts_dir: "{{ scripts_dir }}"
  tasks:
    - name: Run the equivalent of "pacman -Syu" as a separate step
      become: true
      pacman:
      update_cache: yes
      upgrade: yes
    - name: install packages
      become: true
      pacman:
        name: "{{ item }}"
      with_items:
        - alacritty
        - alsa-utils
        - ansible
        - base-devel
        - bat
        - blueman
        - bluez
        - bluez-utils
        # because hangouts
        - chromium
        - dunst
        - element-desktop
        - firefox-developer-edition
        # this probably isn't needed, since you need git to
        # clone the repo locally anyways
        - git
        - gnupg
        - graphviz
        - hugo
        - i3
        - imagemagick
        - keepassx2
        - libinput
        - libreoffice-still
        - msr-tools
        - nautilus
        - neofetch
        - openssh
        - pacman-contrib
        - pavucontrol
        - poppler
        - pulseaudio
        - pulseaudio-alsa
        - pychess
        - ranger
        - ripgrep
        - rofi
        - rust
        - telegram-desktop
        - visual-studio-code-bin
        - vlc
        - xorg
        - yarn # for prometheus
        - zsh
    - name: ensure git directory exists
      file:
        path: /home/callum/git
        state: directory
        owner: callum
        group: callum
        mode: 0755
    - name: install AUR packages
      aur: 
        use: yay
        name: "{{ item }}"
      with_items:
        - lenovo-throttling-fix-git
        - notion-app
        - s-tui
        - slack-desktop
        - stockfish
        - spotify
        - tanka
        - ttf-symbola
        - ttf-unifont
        - visual-studio-code-bin
    - name: change shell to zsh
      become: true   
      shell: chsh -s /usr/bin/zsh callum
    - name: set timezone
      become: true
      shell: timedatectl set-timezone Canada/Pacific
    - name: enable timezone syncing daemon
      become: true
      shell: systemctl enable systemd-timesyncd
